# Generated by Django 3.2.9 on 2021-12-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('query', models.TextField()),
            ],
        ),
    ]
