# Generated by Django 3.2.9 on 2021-11-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_text', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
