# Generated by Django 3.2.9 on 2021-11-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_pic',
            field=models.ImageField(default='', upload_to='university/studentpic'),
        ),
    ]
