# Generated by Django 3.2.9 on 2021-11-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_registartion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registartion',
            new_name='Registration',
        ),
    ]
