# Generated by Django 3.2.9 on 2021-11-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_student_student_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('hod_name', models.CharField(max_length=50)),
                ('hod_pic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_venue', models.CharField(max_length=100)),
            ],
        ),
    ]
