# Generated by Django 3.2.9 on 2021-11-28 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_department_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='events',
            name='event_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='event_organiser',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='event_pic',
            field=models.ImageField(default='', upload_to='university/studentpic'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod_pic',
            field=models.ImageField(default='', upload_to='university/studentpic'),
        ),
    ]
